Repository Shinhan-DaeyeohaeYoung/Backend, pull requests merged in 2025-08, with the labels that each got.

#12 Feat: 상품 및 대여 API 로직 구현 w/ 임의의 회원아이디, 조직아이디
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/IndividualItem.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/IndividualItemStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/Item.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/UnitPhoto.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/IndividualItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/ItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/UnitPhotoRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/service/ItemDomainService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/service/UnitPhotoDomainService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/entity/Rental.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/entity/RentalStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/repository/RentalRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/service/RentalDomainService.java
  daeyo-external-api/build.gradle
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/AdminItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/ItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/AdminItemRegisterDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/ItemDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/PageResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/UnitPhotoDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/AdminItemOrchestrator.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/ItemApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/controller/RentalController.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/dto/RentalDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/service/RentalApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/security/TenantProvider.java
Labels: feat

#24 Feat: QR API, 반납 API 구현
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/IndividualItem.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/UnitPhotoRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/entity/ReturnRequest.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/entity/ReturnRequestStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/repository/ReturnRequestRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/service/ReturnRequestService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-external-api/build.gradle
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/AdminItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/ItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/qr/controller/QrController.java
  daeyo-external-api/src/main/java/com/joeun/api/qr/service/QrService.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/controller/RentalController.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/controller/ReturnRequestController.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/dto/ApproveReturnRequestRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/dto/CancelReturnRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/dto/ReturnRequestCreateRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/dto/ReturnRequestResponse.java
  daeyo-external-api/src/main/resources/application.yml
  scripts/env-start.sh
Labels: feat

#23 Feat: 로그인 구현
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/repository/UserRepository.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/user/UserDomainService.java
  daeyo-external-api/src/main/java/com/joeun/api/exception/UnauthorizedException.java
  daeyo-external-api/src/main/java/com/joeun/api/user/controller/UserController.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserMeResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserSigninRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserSigninResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/user/service/UserService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/LoginUser.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
  daeyo-external-api/src/main/java/com/joeun/global/util/CookieUtil.java
  daeyo-external-api/src/main/java/com/joeun/global/util/JwtAuthFilter.java
  daeyo-external-api/src/main/java/com/joeun/global/util/JwtUtil.java
  daeyo-external-api/src/main/resources/application.yml
Labels: feat

#26 Feat: 계좌 관련 코어 로직 작성
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/university/repository/UniversityRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/repository/UserBankAccountRepository.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/university/UniversityDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/user/UserDomainService.java
  daeyo-external-api/src/main/java/com/joeun/api/university/controller/UniversityController.java
  daeyo-external-api/src/main/java/com/joeun/api/university/dto/UniversityResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/university/service/UniversityService.java
  daeyo-external-api/src/main/java/com/joeun/api/user/controller/UserController.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserBankAccountCreateRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserBankAccountCreateResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserBankAccountResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/UserSignupRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/user/service/UserService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
  daeyo-external-api/src/main/java/com/joeun/global/util/AccountCipher.java
  daeyo-external-api/src/main/resources/application.yml
Labels: feat

#31 Feat: 홀딩 만료 시 트리거 및 폴백 구현
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/notification/entity/NotiType.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/notification/entity/NotiUser.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/notification/entity/Notification.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/notification/service/NotificationRdsService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/dto/ExpiredRentalRow.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/entity/Rental.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/repository/RentalRepository.java
  daeyo-domain/domain-service/src/main/java/com/joeun/config/SchedulerConfig.java
  daeyo-domain/domain-service/src/main/java/com/joeun/global/dto/NotificationRequest.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/worker/HoldExpiryFallbackScheduler.java
  daeyo-external-api/src/main/java/com/joeun/api/notification/dto/NotificationResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/notification/service/NotiUserService.java
  daeyo-external-api/src/main/java/com/joeun/api/notification/service/NotificationService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
Labels: feat

#33 Feat: S3 인프라 로직 구현
  .gitignore
  daeyo-external-api/src/main/java/com/joeun/api/example/controller/ExampleController.java
  daeyo-external-api/src/main/java/com/joeun/api/example/dto/ExampleDto.java
  daeyo-infra/build.gradle
  daeyo-infra/src/main/java/com/joeun/common/ImageType.java
  daeyo-infra/src/main/java/com/joeun/common/PresignResponse.java
  daeyo-infra/src/main/java/com/joeun/config/S3Config.java
  daeyo-infra/src/main/java/com/joeun/infra/aws/s3/service/ImageInfraService.java
  daeyo-infra/src/main/java/com/joeun/infra/aws/s3/service/S3ImageInfraService.java
Labels: feat

#38 Feature/deposit
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/deposit/entity/Deposit.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/deposit/repository/DepositRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/entity/Organization.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/repository/OrganizationRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/university/repository/UniversityPointRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/university/repository/UniversityRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/entity/User.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/repository/UserOrgMembershipRepository.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/deposit/DepositDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/organization/OrganizationDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/university/UniversityDomainService.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/controller/DepositController.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/dto/DepositCreateRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/dto/DepositCreateResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/dto/DepositListDto.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/dto/DepositListResult.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/dto/DepositResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/mapper/DepositMappers.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/service/DepositService.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/controller/OrganizationController.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/dto/MyOrganizationResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/dto/OrganizationJoinRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/dto/UserOrgMembershipResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/service/OrganizationService.java
  daeyo-external-api/src/main/java/com/joeun/api/university/controller/UniversityController.java
  daeyo-external-api/src/main/java/com/joeun/api/university/dto/UniversityPointResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/university/dto/UniversityPointTopItem.java
  daeyo-external-api/src/main/java/com/joeun/api/university/dto/UniversityPointTopResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/university/service/UniversityService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
  daeyo-external-api/src/main/resources/application.yml
Labels: feat

#37 Fix: 반납,대여 api , 로직 수정
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/IndividualItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/UnitPhotoRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/entity/Rental.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/repository/RentalRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/repository/ReturnRequestRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/service/ReturnRequestService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/returnrequest/ReturnRequestQueryService.java
  daeyo-external-api/build.gradle
  daeyo-external-api/src/main/java/com/joeun/api/gpt/dto/DamageSuggestionResult.java
  daeyo-external-api/src/main/java/com/joeun/api/gpt/service/DamageAssessmentService.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/controller/RentalController.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/dto/RentalDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/service/RentalApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/controller/ReturnRequestController.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/controller/ReturnRequestDamageController.java
  daeyo-external-api/src/main/java/com/joeun/api/user/controller/UserController.java
  daeyo-external-api/src/main/java/com/joeun/global/config/OpenAiClientConfig.java
  daeyo-external-api/src/main/java/com/joeun/global/config/OpenAiProperties.java
  daeyo-external-api/src/main/java/com/joeun/global/config/StaticMockConfig.java
  daeyo-external-api/src/main/java/com/joeun/global/file/FileProperties.java
  daeyo-external-api/src/main/java/com/joeun/global/file/FileUrlResolver.java
  daeyo-external-api/src/main/resources/application.yml
  daeyo-external-api/src/main/resources/mock/sample.jpg
Labels: bug

#41 Fix: s3사진 업로드 로직 구현, jwt 통한 user 정보 전달 컨트롤러 수정
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/Item.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/ItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/service/ItemDomainService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/repository/OrganizationRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/service/ReturnRequestService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-external-api/src/main/java/com/joeun/api/image/controller/ImageController.java
  daeyo-external-api/src/main/java/com/joeun/api/image/dto/PresignUploadRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/AdminItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/ItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/UnitPhotoDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/AdminItemOrchestrator.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/ItemApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/qr/controller/QrController.java
  daeyo-external-api/src/main/java/com/joeun/api/qr/service/QrService.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/controller/RentalController.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/service/RentalApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/controller/ReturnRequestController.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/service/ReturnRequestApplicationService.java
  daeyo-external-api/src/main/resources/application.yml
Labels: feat

#43 Feat: 대기열 로직 구현 및 대여, 상품 API 버그 수정
  Dockerfile
  build.gradle
  daeyo-batch/build.gradle
  daeyo-common/build.gradle
  daeyo-domain/build.gradle
  daeyo-domain/domain-rds/build.gradle
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/holding/entity/Holding.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/holding/entity/HoldingStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/holding/repository/HoldingRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/IndividualItem.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/IndividualItemStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/Item.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/IndividualItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/repository/ItemRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/service/ItemDomainService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/dto/ExpiredRentalRow.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/rental/repository/RentalRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/repository/UserOrgMembershipRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/waitlist/entity/Waitlist.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/waitlist/entity/WaitlistStatus.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/waitlist/repository/WaitlistRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/waitlist/service/WaitlistRdsService.java
  daeyo-domain/domain-redis/build.gradle
  daeyo-domain/domain-redis/src/main/java/com/joeun/domain/reservation/service/ReservationRedisService.java
  daeyo-domain/domain-service/build.gradle
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/returnrequest/ReturnRequestService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/waitlist/WaitlistDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/worker/HoldExpiryFallbackScheduler.java
  daeyo-external-api/build.gradle
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/ItemDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/ItemApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/notification/service/NotificationService.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/service/ReturnRequestApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/waitlist/api/WaitlistApi.java
  daeyo-external-api/src/main/java/com/joeun/api/waitlist/controller/WaitlistController.java
  daeyo-external-api/src/main/java/com/joeun/api/waitlist/dto/WaitlistPositionByItemResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/waitlist/service/WaitlistService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
  daeyo-external-api/src/main/resources/application-prod.yml
  daeyo-infra/build.gradle
Labels: bug, feat

#48 Fix: qr 권한 문제 해결, 토큰 헤더추가 문제 해결
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/AdminItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/controller/ItemController.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/ItemApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/qr/controller/QrController.java
Labels: feat

#50 Fix: QR 인증 í수정
  daeyo-external-api/src/main/java/com/joeun/api/qr/controller/QrController.java
  daeyo-external-api/src/main/java/com/joeun/global/config/SecurityConfig.java
Labels: feat

#54 Chore: 사진 url 전체로 제공
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/ItemDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/UnitPhotoDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/service/ItemApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/service/ReturnRequestApplicationService.java
  daeyo-infra/src/main/java/com/joeun/infra/aws/s3/service/S3ImageInfraService.java
Labels: feat

#63 Feat: 일간 물품별 대여 횟수 및 연체 횟수 조회 Swagger
  daeyo-external-api/src/main/java/com/joeun/api/statistics/api/StatisticsApi.java
  daeyo-external-api/src/main/java/com/joeun/api/statistics/controller/StatisticsController.java
Labels: feat

#69 Feature/ssafy api
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/entity/Item.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/item/service/ItemDomainService.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/entity/OrgApiCredential.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/entity/OrgBankAccount.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/entity/Organization.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/repository/OrgApiCredentialRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/organization/repository/OrganizationRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/returnrequest/repository/ReturnRequestRepository.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/entity/User.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/entity/UserApiCredential.java
  daeyo-domain/domain-rds/src/main/java/com/joeun/domain/users/repository/UserApiCredentialRepository.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/organization/OrganizationDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/rental/RentalDomainService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/returnrequest/ReturnRequestService.java
  daeyo-domain/domain-service/src/main/java/com/joeun/service/user/UserDomainService.java
  daeyo-external-api/build.gradle
  daeyo-external-api/src/main/java/com/joeun/DaeyoExternalApiApplication.java
  daeyo-external-api/src/main/java/com/joeun/api/deposit/service/DepositService.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/AdminItemRegisterDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/item/dto/ItemDtos.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/controller/OrganizationController.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/dto/OrgBankAccountResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/mapper/OrgBankAccountMappers.java
  daeyo-external-api/src/main/java/com/joeun/api/organization/service/OrganizationService.java
  daeyo-external-api/src/main/java/com/joeun/api/rental/service/RentalApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/returnrequest/service/ReturnRequestApplicationService.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/HeaderFactory.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/SsafyApiException.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/SsafyBankClient.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/SsafyErrorDecoder.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/client/SsafyDemandDepositClient.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/client/SsafyMemberClient.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/AccountApiHeader.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/ApiHeader.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/CreateDemandDepositAccountRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/CreateDemandDepositAccountResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/InquireDemandDepositAccountBalanceRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/InquireDemandDepositAccountBalanceResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/MemberCreateRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/MemberCreateResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/UpdateDemandDepositAccountDepositRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/UpdateDemandDepositAccountDepositResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/UpdateDemandDepositAccountTransferRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/ssafyAPI/dto/UpdateDemandDepositAccountTransferResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/students/dto/StudentSignupRequest.java
  daeyo-external-api/src/main/java/com/joeun/api/students/service/StudentService.java
  daeyo-external-api/src/main/java/com/joeun/api/user/controller/UserController.java
  daeyo-external-api/src/main/java/com/joeun/api/user/dto/MyBalanceResponse.java
  daeyo-external-api/src/main/java/com/joeun/api/user/service/UserService.java
  daeyo-external-api/src/main/java/com/joeun/global/config/FeignConfig.java
  daeyo-external-api/src/main/resources/application.yml
Labels: feat
